# Generated by Django 5.2 on 2025-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_de_naissaince', models.DateField()),
                ('lieu_de_naissaince', models.CharField(max_length=100)),
                ('mention', models.CharField(max_length=100)),
                ('parcours', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('niveau', models.IntegerField()),
                ('numero_d_incription', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
