# Generated by Django 5.2 on 2025-04-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFac', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('email', models.EmailField(max_length=254)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMention', models.CharField(max_length=100)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.facultes')),
                ('chefMention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomParcours', models.CharField(max_length=100)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.mention')),
                ('proff_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNiveau', models.CharField(max_length=100)),
                ('parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCours', models.CharField(max_length=100)),
                ('id_parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.parcours')),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('numero_d_inscription', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.mention')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='facultes',
            name='directeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher'),
        ),
    ]
