# Generated by Django 5.2 on 2025-04-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='numero_d_incription',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
