# Generated by Django 5.2 on 2025-04-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_alter_students_numero_d_incription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='date_de_naissaince',
            new_name='date_de_naissance',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='gender',
            new_name='lieu_de_naissance',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='lieu_de_naissaince',
            new_name='sexe',
        ),
    ]
