# Generated by Django 5.2 on 2025-04-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_rename_date_de_naissaince_students_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='numero_d_incription',
            new_name='numero_d_inscription',
        ),
    ]
