# Generated by Django 5.2 on 2025-04-07 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_rename_numero_d_incription_students_numero_d_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomParcours', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCours', models.CharField(max_length=100)),
                ('id_parcour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.parcours')),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='parcours',
            name='proff_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.teacher')),
            ],
        ),
    ]
